export {default as Header} from './header/Header'
export {default as Main} from './main/Main'
export {default as Container} from './ui/Container'
export {default as ServiceCard} from './card/service.card'
export {default as ServicesFilter} from './servicesFilter/ServicesFilter'
export {default as Filter} from './filter/filter'
export {default as Rectangle} from './Rectangle/Rectanglepage'
export {default as Gardenpage} from './garden/Gardenpage'
export {default as clientss} from './clientss/clientpage'
export {default as Link} from './link/linkpage'

