export {default as Header} from './header/Header'
export {default as Main} from './main/Main'
export {default as Container} from './ui/Container'
export {default as ServiceCard} from './card/service.card'
export {default as MainHeading} from './ui/MainHeading'
export {default as ServiceArea} from './serviceArea/ServiceArea'
export {default as Footer} from './footer/Footer'